<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>boo</string>
	</array>
	<key>name</key>
	<string>C++ Error Output</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#pars</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bracs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#anglebracs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#curlies</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((e|E)rror)\b</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(warning|instantiation|note|required|candidate)</string>
			<key>name</key>
			<string>markup.quote</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[^\:\s]*(?=:)</string>
			<key>name</key>
			<string>support.variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=:)[0-9]+</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>anglebracs</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!&lt;)\&lt;(?!\&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.raw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>pars</string>
				</dict>
			</array>
		</dict>
		<key>bracs</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.quote</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>anglebracs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>pars</string>
				</dict>
			</array>
		</dict>
		<key>curlies</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.list</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>anglebracs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>pars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>bracs</string>
				</dict>
			</array>
		</dict>
		<key>pars</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\)|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>anglebracs</string>
				</dict>
			</array>
		</dict>
		<key>quotes</key>
		<dict>
			<key>begin</key>
			<string>‘</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>’</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bold</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>anglebracs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>pars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>bracs</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.boo</string>
	<key>uuid</key>
	<string>45319b4d-90f8-4ff1-9a66-c56ed5c408a4</string>
</dict>
</plist>
