<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>in</string>
	</array>
	<key>name</key>
	<string>Skeleton Composition Input</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(input|output)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;=\=)[^\[]*)</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[[\w\(\)\s]+\])</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[[^\]]+$)</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(.*\=)</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#.*)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.in</string>
	<key>uuid</key>
	<string>ff1ac1fd-274f-4550-86c6-6addba6f084b</string>
</dict>
</plist>
